name: Build & deploy

on:
  push:
    branches: [dependant]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependancies
        run: pnpm i
      - name: Running build
        run: pnpm run build
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: second job 1 step
        run: echo "second job 1"
      - name: second 2
        run: echo "second 2"
